In [1]:
# 1. Import Libraries
import pandas as pd
import numpy as np
import os
import requests
import json
from datetime import datetime

In [2]:
# 2. Read in and Merge the CitiBike 2022 Files

# Updated folder path where 2022 CSV files are stored
folder_path = r'/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata'

In [5]:
file_paths = [os.path.join(folder_path, name) for name in os.listdir(folder_path) if name.endswith('.csv')]

In [7]:
file_paths

['/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202208-citibike-tripdata_3.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202207-citibike-tripdata_2.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202207-citibike-tripdata_3.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202208-citibike-tripdata_2.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202207-citibike-tripdata_1.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202208-citibike-tripdata_1.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202210-citibike-tripdata_1.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202207-citibike-tripdata_4.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202208-citibike-tripdata_4.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202203-citibike-tripdata_2.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202210-citibike-tripdata_2.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202203-citibike-tripdata_1.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202210-citibike-tripdata_3.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202204-citibike-tripdata_1.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202204-citibike-tripdata_2.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202204-citibike-tripdata_3.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202211-citibike-tripdata_3.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202202-citibike-tripdata_1.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202211-citibike-tripdata_2.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202202-citibike-tripdata_2.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202209-citibike-tripdata_4.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202206-citibike-tripdata_4.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202211-citibike-tripdata_1.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202209-citibike-tripdata_1.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202206-citibike-tripdata_1.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202206-citibike-tripdata_3.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202209-citibike-tripdata_2.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202209-citibike-tripdata_3.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202206-citibike-tripdata_2.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202205-citibike-tripdata_3.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202205-citibike-tripdata_2.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202205-citibike-tripdata_1.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202201-citibike-tripdata_2.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202212-citibike-tripdata_1.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202201-citibike-tripdata_1.csv',
 '/Users/samarjitgehdu/Documents/Achievement 2/2022-citibike-tripdata/202212-citibike-tripdata_2.csv']

In [9]:
# Read and concatenate all files simultaneously

df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)

/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)
/var/folders/zl/tcc09dfs4v13063yfphqmzjr0000gn/T/ipykernel_3222/1222133079.py:3: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.concat((pd.read_csv(f) for f in file_paths), ignore_index = True)

In [11]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,9D0DC440CB40CF8E,electric_bike,2022-08-27 13:56:47.728,2022-08-27 14:02:56.651,Flatbush Ave & Ocean Ave,3704.04,3 St & Prospect Park West,3865.05,40.663657,-73.963014,40.668132,-73.973638,casual
1,2214991DFBE5C4D7,electric_bike,2022-08-20 10:37:02.756,2022-08-20 10:45:56.631,Forsyth St\t& Grand St,5382.07,E 11 St & 1 Ave,5746.14,40.717798,-73.993161,40.729538,-73.984267,casual
2,20C5D469563B6337,classic_bike,2022-08-31 18:55:03.051,2022-08-31 19:03:37.344,Perry St & Bleecker St,5922.07,Grand St & Greene St,5500.02,40.735354,-74.004831,40.721700,-74.002381,member
3,3E8791885BC189D1,classic_bike,2022-08-02 08:05:00.250,2022-08-02 08:16:52.063,FDR Drive & E 35 St,6230.04,Grand Army Plaza & Central Park S,6839.10,40.744219,-73.971212,40.764397,-73.973715,member
4,8DBCBF98885106CB,electric_bike,2022-08-25 15:44:48.386,2022-08-25 15:55:39.691,E 40 St & 5 Ave,6474.11,Ave A & E 14 St,5779.11,40.752052,-73.982115,40.730311,-73.980472,member


#### The code creates a list of all file paths in the specified folder.
#### It reads each CSV individually and merges all monthly trip data into a single DataFrame.

In [14]:
# 3. NOAA Token Registration
# Register on NOAA site and get individual API token

In [16]:
# 4. Obtain Weather Data for LaGuardia Airport (2022)
Token = 'ICSDUvhITNDqcYHqyUKtWTCxQbTwBxBB'  
response = requests.get(
    'https://www.ncdc.noaa.gov/cdo-web/api/v2/data?datasetid=GHCND&datatypeid=TAVG&limit=1000&stationid=GHCND:USW00014732&startdate=2022-01-01&enddate=2022-12-31',
    headers={'token': Token}
)

In [18]:
weather_data = json.loads(response.text)

In [22]:
# 5. Extract Dates and Temperatures
avg_temps = [item for item in weather_data['results'] if item['datatype'] == 'TAVG']

In [24]:
dates_temp = [item['date'] for item in avg_temps]

In [26]:
temps = [item['value'] for item in avg_temps]

In [28]:
# 6. Create Weather DataFrame and Export to CSV
df_temp = pd.DataFrame()

In [30]:
df_temp['date'] = [datetime.strptime(d, "%Y-%m-%dT%H:%M:%S") for d in dates_temp]

In [32]:
df_temp['avgTemp'] = [float(v) / 10.0 for v in temps]

In [34]:
df_temp.to_csv('Weather_Data_2022.csv', index=False) # Export to CSV

In [36]:
# Verify the Generated CSV file
df_temp.head()

        date  avgTemp
0 2022-01-01     11.6
1 2022-01-02     11.4
2 2022-01-03      1.4
3 2022-01-04     -2.7
4 2022-01-05      3.2

In [40]:
# 7. Verify and Prepare CitiBike Data for Merge

# Check actual column names
print(df.columns)

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='object')

In [42]:
# Verify Weather Data 2022 for Merge

# Check actual column names
print(df_temp.columns)

Index(['date', 'avgTemp'], dtype='object')

In [44]:
# Prepare for merger
df['started_at'] = pd.to_datetime(df['started_at'])

In [46]:
df['date'] = df['started_at'].dt.date

In [50]:
# Fix data types before merging( Dtype should both to same being "datetime")
df['date'] = pd.to_datetime(df['date'])
df_temp['date'] = pd.to_datetime(df_temp['date'])

In [52]:
# 8. Merge CitiBike Trip Data with Weather Data
df_merged = df.merge(df_temp, how='left', on='date', indicator=True)

In [56]:
# verify the merged file
df_merged.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,date,avgTemp,_merge
0,9D0DC440CB40CF8E,electric_bike,2022-08-27 13:56:47.728,2022-08-27 14:02:56.651,Flatbush Ave & Ocean Ave,3704.04,3 St & Prospect Park West,3865.05,40.663657,-73.963014,40.668132,-73.973638,casual,2022-08-27,27.8,both
1,2214991DFBE5C4D7,electric_bike,2022-08-20 10:37:02.756,2022-08-20 10:45:56.631,Forsyth St\t& Grand St,5382.07,E 11 St & 1 Ave,5746.14,40.717798,-73.993161,40.729538,-73.984267,casual,2022-08-20,27.9,both
2,20C5D469563B6337,classic_bike,2022-08-31 18:55:03.051,2022-08-31 19:03:37.344,Perry St & Bleecker St,5922.07,Grand St & Greene St,5500.02,40.735354,-74.004831,40.721700,-74.002381,member,2022-08-31,25.6,both
3,3E8791885BC189D1,classic_bike,2022-08-02 08:05:00.250,2022-08-02 08:16:52.063,FDR Drive & E 35 St,6230.04,Grand Army Plaza & Central Park S,6839.10,40.744219,-73.971212,40.764397,-73.973715,member,2022-08-02,26.4,both
4,8DBCBF98885106CB,electric_bike,2022-08-25 15:44:48.386,2022-08-25 15:55:39.691,E 40 St & 5 Ave,6474.11,Ave A & E 14 St,5779.11,40.752052,-73.982115,40.730311,-73.980472,member,2022-08-25,28.1,both

In [58]:
# Export the Merged CSV file
df_merged.to_csv('CitiBike_Weather_Merged_2022.csv', index=False)